name: Renovate Bot Runner
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      
      - name: Run Renovate via NPX
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: debug
        run: npx renovate