name: Renovate Bot Runner
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      
      - name: Run Renovate via NPX
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: debug
        run: npx renovate